# Generated by Django 5.1.4 on 2025-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ai_style',
        ),
        migrations.RemoveField(
            model_name='article',
            name='dress_style',
        ),
        migrations.RemoveField(
            model_name='article',
            name='location',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d/'),
        ),
    ]
