# Generated by Django 5.1.4 on 2025-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='내용을 입력하세요 (필수사항)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='이미지를 업로드하세요 (선택사항)', null=True, upload_to='articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, help_text='공개 여부를 설정하세요 (기본값: 공개)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, help_text='제목을 입력하세요 (선택사항)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='조회수 (자동 집계)'),
        ),
    ]
