# Generated by Django 5.1.4 on 2025-01-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 사용 중인 이메일입니다.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, help_text='자기소개를 입력하세요.'),
        ),
    ]
