# Generated by Django 5.1.4 on 2025-01-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 사용 중인 이메일입니다.'}, help_text='로그인에 사용할 이메일 주소를 입력하세요. (필수)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, help_text='자기소개를 입력하세요. (선택사항)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='프로필 이미지를 업로드하세요. (선택사항)', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 사용자 이름입니다.'}, help_text='사용자 이름을 입력하세요. (필수)', max_length=150, unique=True),
        ),
    ]
