# Generated by Django 5.1.4 on 2025-01-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('naver', '네이버'), ('kakao', '카카오'), ('google', '구글'), ('email', '이메일')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 사용자 이름입니다.'}, help_text='사용자 이름을 입력하세요. (필수)', max_length=150),
        ),
    ]
