name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        debug: true
        command_timeout: 200m
        script: |
          cd /home/ubuntu/whyding
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          docker ps
          docker-compose logs
